### ISSUE TITLE
RFE: Add a method to reverse_geocode from eastings/northings to GSP IDs

### ISSUE THREAD

**Issue by JulianBriggs** [SheffieldSolar/Geocode#20]
RFE
Add a method to reverse_geocode from eastings/northings to GSP IDs. 
ECR provides eastings/northings.
Currently I convert these to lat/lon, then call  reverse_geocode_gsp with the lat/lons
which then converts them back to eastings/northings to derive the GSP IDs
Thanks. 
kr 
J

**Comment by JamieTaylor-TUOS** [comment]
@JulianBriggs there are a couple of options to achieve this:

1. Use the `bng2latlon` method in the [utilities.py](https://github.com/SheffieldSolar/Geocode/blob/master/geocode/utilities.py) of the Geocode package:
```python
from geocode.utilities import bng2latlon

eastings = [7814454.923640898, 8016746.777431069]
northings = [-5751449.462009629, -5557116.162734557]
latitudes, longitudes = bng2latlon(eastings, northings)
print(latitudes, longitudes)
```
```
[53.22999999999511, 54.229999999991485] [-1.1499999999974109, -0.14999999999944638]
```

2. Use Geopandas:
```python
import pandas as pd
import geopandas as gpd

df = pd.DataFrame({"eastings": [7814454.923640898, 8016746.777431069], "northings": [-5751449.462009629, -5557116.162734557]})
gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df.eastings, df.northings),
    crs="EPSG:27700"
).to_crs("EPSG:4326")
latitudes, longitudes = gdf.geometry.x.values, gdf.geometry.y.values
print(latitudes, longitudes)
```
```
[53.23 54.23] [-1.15 -0.15]
```

In general, I would like to move towards this package working entirely with Geopandas GeoDataFrames, such that CRS information and conversions are handled automatically, but that will take some time to implement (see this issue: #6 )...
